cameras:
  - id: abbey_road
    name: "Abbey Road Crossing"
    location: "Londres, UK"
    url: "https://www.youtube.com/live/M3EYAY2MftI"
    active: true
    classes: ["person"]
    interval_minutes: 5

  - id: shibuya
    name: "Shibuya Crossing"
    location: "Tokyo, Japon"
    url: "https://www.youtube.com/live/dfVK7ld38Ys"
    active: true
    classes: ["person"]
    interval_minutes: 5
